rule all:
	input:
		expand("results/{dataset}.txt", dataset = ["A", "B"])

rule test:
	output:
		result="results/{dataset}.txt"
	conda:
		"conda/bash.yaml"
	log:
		"log/{dataset}.log"
	shell:
		"""
		echo {wildcards.dataset} > {output}
		echo "Dataset {wildcards.dataset} done" > {log}
		"""
