rule all:
	input:
		expand("results/{dataset}.txt", dataset = ["A", "B"])

rule test:
	output:
		result="results/{dataset}.txt"
	conda:
		"conda/bash.yaml"
	shell:
		"""
		echo {wildcards.dataset} > {output}
		"""
