name: simple-workflow
run-name: ${{ github.actor }} is testing Snakemake
on: [push]
jobs:
  run-snakemake-basic-tests:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Linting
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--lint'
      - name: Testing
        uses: snakemake/snakemake-github-action@v1
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
          #stagein: '' # additional preliminary commands to run (can be multiline)
      # - name: Create container file
      #   uses: snakemake/snakemake-github-action@v1
      #   with:
      #     snakefile: 'workflow/Snakefile'
      #     task: 'containerize'
